# Generated by Django 5.0.1 on 2024-02-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_category_subscribers_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_date', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.subscription')),
            ],
        ),
    ]
